### ISSUE TITLE
Linux Mint 18.2 Exception

### ISSUE THREAD

**Issue by r3d9u11** [ozmartian/vidcutter#109]
Hi, I tried to run in Linux Mint 18.2 x64 (Mate), but got exception:
```
$ vidcutter
Traceback (most recent call last):
  File "/usr/bin/vidcutter", line 9, in <module>
    load_entry_point('vidcutter==5.0.0', 'gui_scripts', 'vidcutter')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/vidcutter/__main__.py", line 41, in <module>
    from vidcutter.videocutter import VideoCutter
  File "/usr/lib/python3/dist-packages/vidcutter/videocutter.py", line 43, in <module>
    from vidcutter.libs.mpvwidget import mpvWidget
  File "/usr/lib/python3/dist-packages/vidcutter/libs/mpvwidget.py", line 12, in <module>
    from OpenGL import GL
  File "/usr/lib/python3/dist-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/usr/lib/python3/dist-packages/OpenGL/GL/VERSION/GL_1_1.py", line 10, in <module>
    from OpenGL import platform, constants, constant, arrays
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/__init__.py", line 22, in <module>
    formathandler.FormatHandler.loadAll()
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/formathandler.py", line 28, in loadAll
    cls.loadPlugin( entrypoint )
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/formathandler.py", line 35, in loadPlugin
    plugin_class = entrypoint.load()
  File "/usr/lib/python3/dist-packages/OpenGL/plugins.py", line 14, in load
    return importByName( self.import_path )
  File "/usr/lib/python3/dist-packages/OpenGL/plugins.py", line 28, in importByName
    module = __import__( ".".join(moduleName), {}, {}, moduleName)
  File "/usr/lib/python3/dist-packages/OpenGL/arrays/vbo.py", line 430, in <module>
    def mapVBO( vbo, access=GL.GL_READ_WRITE ):
AttributeError: module 'OpenGL.GL' has no attribute 'GL_READ_WRITE'
```
Any ideas?
Thank.s

**Comment by ozmartian** [comment]
Hi @r3d9u11,



This is due to version differences with older PyOpenGL versions when used with newer libmpv versions I think. A fix is currently in the works and should be ready for release with a day or two at most. PyOpenGL is being completely removed as a dependency as its no longer needed and was only there to address problems with earlier versions of Ubuntu which had a buggy PyQt5 in the core repos. Also means future releases should all work on release day now that these types of "hacky" workarounds can be removed.



I must confess that I did forget to test on Mint before releasing v5.0.0. Typically, as is always the case in IT, the one time you forget to test on a specific system also happens to be the one time that system stops working due to obscure edge cases like this :-)



Apologies to you first :-) and a promise to test on Mint 18.2 once the changes for the patch release are complete.



Cheers + thanks,

Pete




---- On Fri, 24 Nov 2017 01:44:39 +0800 r3d9u11 &lt;notifications@github.com&gt; wrote ----




Hi, I tried to run it in Linux Mint 18.2 x64 (Mate), but got exception:

$ vidcutter Traceback (most recent call last): File "/usr/bin/vidcutter", line 9, in &lt;module&gt; load_entry_point('vidcutter==5.0.0', 'gui_scripts', 'vidcutter')() File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point return get_distribution(dist).load_entry_point(group, name) File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point return ep.load() File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load return self.resolve() File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve module = __import__(self.module_name, fromlist=['__name__'], level=0) File "/usr/lib/python3/dist-packages/vidcutter/__main__.py", line 41, in &lt;module&gt; from vidcutter.videocutter import VideoCutter File "/usr/lib/python3/dist-packages/vidcutter/videocutter.py", line 43, in &lt;module&gt; from vidcutter.libs.mpvwidget import mpvWidget File "/usr/lib/python3/dist-packages/vidcutter/libs/mpvwidget.py", line 12, in &lt;module&gt; from OpenGL import GL File "/usr/lib/python3/dist-packages/OpenGL/GL/__init__.py", line 3, in &lt;module&gt; from OpenGL.GL.VERSION.GL_1_1 import * File "/usr/lib/python3/dist-packages/OpenGL/GL/VERSION/GL_1_1.py", line 10, in &lt;module&gt; from OpenGL import platform, constants, constant, arrays File "/usr/lib/python3/dist-packages/OpenGL/arrays/__init__.py", line 22, in &lt;module&gt; formathandler.FormatHandler.loadAll() File "/usr/lib/python3/dist-packages/OpenGL/arrays/formathandler.py", line 28, in loadAll cls.loadPlugin( entrypoint ) File "/usr/lib/python3/dist-packages/OpenGL/arrays/formathandler.py", line 35, in loadPlugin plugin_class = entrypoint.load() File "/usr/lib/python3/dist-packages/OpenGL/plugins.py", line 14, in load return importByName( self.import_path ) File "/usr/lib/python3/dist-packages/OpenGL/plugins.py", line 28, in importByName module = __import__( ".".join(moduleName), {}, {}, moduleName) File "/usr/lib/python3/dist-packages/OpenGL/arrays/vbo.py", line 430, in &lt;module&gt; def mapVBO( vbo, access=GL.GL_READ_WRITE ): AttributeError: module 'OpenGL.GL' has no attribute 'GL_READ_WRITE' 
Any ideas?

 Thank.s

**Comment by ozmartian** [comment]
FYI,

Keeping this issue open pending release of patch release as a super minor version change 5.0.5

**Comment by armageddon51** [comment]
Was about to post the same error but thank you very much for looking at the issue. Got it Mint Cinnamon 18.2. Great program !!

**Comment by r3d9u11** [comment]
@ozmartian thanks! works fine now. Linux Mint 18.3 x64, vidcutter v5.0.5
think issue can be closed
