### ISSUE TITLE
vidcutter won't start after recent update

### ISSUE THREAD

**Issue by usamakh** [ozmartian/vidcutter#11]
@ Debian 7.0 x32 ...via ppa
THis issue occured after getting recent update ...before that running flawless

> vidcutter
> Traceback (most recent call last):
>   File "/usr/bin/vidcutter", line 9, in <module>
>     load_entry_point('vidcutter==2.6.5', 'gui_scripts', 'vidcutter')()
>   File "/usr/lib/python3/dist-packages/vidcutter/__main__.py", line 144, in main
>     win = MainWindow()
>   File "/usr/lib/python3/dist-packages/vidcutter/__main__.py", line 23, in __init__
>     self.init_logging()
>   File "/usr/lib/python3/dist-packages/vidcutter/__main__.py", line 49, in init_logging
>     log_path = QStandardPaths.writableLocation(QStandardPaths.AppConfigLocation).lower()
> AttributeError: type object 'QStandardPaths' has no attribute 'AppConfigLocation'
>

**Comment by ozmartian** [comment]
thanks for the writing in.. from your error message it appears that you're running a version of Qt that is older than 5.5 which has always been the minimum BUT since you say all was still working well for you I can easily push a patch in to the PPA that should solve this for you. Should be a 5min task.

Will advise when its ready and just so we're sure, can you confirm your version of Qt? Just quote the version number displayed in the About Qt menu option (via right-click or menu button in bottom right)

**Comment by ozmartian** [comment]
hey there...

the patch has been applied and pushed up to the PPA repository so just install the latest update when prompted and you should no longer have issues with log file path.

Cheers!

**Comment by usamakh** [comment]
Extreme thanks for your reply as your application has no Linux alternative

> qmake --version
> QMake version 2.01a
> Using Qt version 4.8.6 in /usr/lib/i386-linux-gnu

and

> pkg-config --modversion QtCore
> 4.8.6

...regarding patch I will update tomorrow

**Comment by ozmartian** [comment]
thanks...

that output shows Qt4 but you definitely would have 5 also installed otherwise VidCutter never would have worked.. I am confident the recent patch update will get things working for you unless there is some other issue in addition to the one just fixed but I've tested on fairly old distributions without fail.

Basically, as long as your system can run mpv and ffmpeg your good to go.

Will look out for your message to see how it went...

Cheers!

**Comment by usamakh** [comment]
Now its throwing this error ..on Bunsenlab (Debian x32) I am using Xenial PPA via Synaptic Packet Manager

>  vidcutter
> Traceback (most recent call last):
>   File "/usr/bin/vidcutter", line 9, in <module>
>     load_entry_point('vidcutter==3.0.0', 'gui_scripts', 'vidcutter')()
>   File "/usr/lib/python3/dist-packages/pkg_resources.py", line 356, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2476, in load_entry_point
>     return ep.load()
>   File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2190, in load
>     ['__name__'])
>   File "/usr/lib/python3/dist-packages/vidcutter/__main__.py", line 38, in <module>
>     from vidcutter.videocutter import VideoCutter
>   File "/usr/lib/python3/dist-packages/vidcutter/videocutter.py", line 40, in <module>
>     import vidcutter.mpv as mpv
>   File "/usr/lib/python3/dist-packages/vidcutter/mpv.py", line 321, in <module>
>     _handle_func('mpv_create_client', [c_char_p], MpvHandle, notnull_errcheck)
>   File "/usr/lib/python3/dist-packages/vidcutter/mpv.py", line 274, in _handle_func
>     func = getattr(backend, name)
>   File "/usr/lib/python3.4/ctypes/__init__.py", line 364, in __getattr__
>     func = self.__getitem__(name)
>   File "/usr/lib/python3.4/ctypes/__init__.py", line 369, in __getitem__
>     func = self._FuncPtr((name_or_ordinal, self))
> AttributeError: /usr/lib/i386-linux-gnu/libmpv.so.1: undefined symbol: mpv_create_client

My system can run mpv as well as ffmpeg... please do help
Package versions installed
https://i.imgur.com/tWL5buJ.png
