### ISSUE TITLE
Vidcutter crashes instantly after opening any videofiles

### ISSUE THREAD

**Issue by martinkg** [ozmartian/vidcutter#130]
Description: Vidcutter starts up fine, but as soon as I try to open any videofile (doesn't matter if it is MPEG2, MPEG4, avi, whatever) the application crashes/closes itself instantly. The crashes happen with SD- & HD-videos and every videoformat-/container I tested it with. Tried it with smart-cut on/off and Hardware-decoding on/off, but both didn't make a difference. 

Starting Vidcutter via terminal gives no output at all when it crashes, therefore I started Vidcutter with strace. This part at the end seems to be relevant and led to the crashes: 

openat(AT_FDCWD, "/lib64/tls/GL", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/lib64/GL", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib64/tls/GL", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib64/GL", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
munmap(0x7f9c866a8000, 145880)          = 0
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
+++ killed by SIGSEGV (core dumped) +++
Speicherzugriffsfehler (Speicherabzug geschrieben)

Speicherzugriffsfehler = Segmentation fault 

The problem is that vidcutter (or any dependency) try to dlopen the unversioned libGL.so whereas it should use libGL.so.1.

**Comment by ozmartian** [comment]
This seems to be an issue specific to Fedora and Ubuntu (Xenial and earlier). Can you give me some more details on your system like Linux distro and version, how to you installed VidCutter (Linux package Arch/openSUSE/Fedora/Ubuntu repositories / AppImage / Directly running source code etc.). Also your Video card brand and model would be useful.



FYI, besides strace, you can run vidcutter from terminal with "--debug" parameter and that will output useful information which is also logged to a log file under /home/&lt;your_home_folder&gt;/.config/vidcutter/vidcutter.log so either cp[y/paste relevant output from terminal with "--debug" or attach most recent block from logs.



I am pretty sure this issue has already been addressed and fixed in DEV for v5.5.0 which I plan to release sometime this week.



If you have the time and are keen to help out :-) The fix for this weird case you are in (its hard to replicate is why I say weird cause VidCutter is not concerned with which libs are called etc, thats all handled by libmpv so i think its more a OpenGL specific issue with some Linux distributions, the error coming from the distro maintainers (Ubuntu and Fedora are definitely at fault in the past but all latest releases have since been all good in my thorough testing... If you can, try carrying out the following steps with VidCutter installed via your package manager. Before you begin, you will need to install an extra python3 module PyOpenGL which might already be installed. So using your package manager install "python3-opengl" or "python3-pyopengl" (depending on your flavour of Linux). If you cannot find it then you can easily install it using pip in a terminal:



   $ sudo pip3 install PyOpenGL



And then edit the following Python source code file as root (vi or pico etc.) - on Ubuntu: /usr/lib/python3/dist-packages/vidcutter/libs/mpvwidget.py on Arch/Fedora/openSUSE: /usr/lib64/python3.6/site-packages/vidcutter/libs/mpvwidget.py



insert the following line of code at the top, above the PyQt5 import block of code:



    from OpenGL import GL



so that it should now look like:



    import locale

    import logging

    import os

    import sys



    from OpenGL import GL



    from PyQt5.QtCode import ......





run the app now like you normally would, don't forget the "--debug" so you report back if still problems..



thanks a lot, the above is all voluntary :-)



oh one last thing.. have your confirmed that OpenGL libs and mesa/libva are working fine on your machine? use the "vainfo" and "vdpauinfo" tools to find out




---- On Tue, 30 Jan 2018 22:37:03 +0800 martinkg &lt;notifications@github.com&gt; wrote ----




Description: Vidcutter starts up fine, but as soon as I try to open any videofile (doesn't matter if it is MPEG2, MPEG4, avi, whatever) the application crashes/closes itself instantly. The crashes happen with SD- &amp; HD-videos and every videoformat-/container I tested it with. Tried it with smart-cut on/off and Hardware-decoding on/off, but both didn't make a difference.

Starting Vidcutter via terminal gives no output at all when it crashes, therefore I started Vidcutter with strace. This part at the end seems to be relevant and led to the crashes:

openat(AT_FDCWD, "/lib64/tls/GL", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

 openat(AT_FDCWD, "/lib64/GL", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

 openat(AT_FDCWD, "/usr/lib64/tls/GL", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

 openat(AT_FDCWD, "/usr/lib64/GL", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)

 munmap(0x7f9c866a8000, 145880) = 0

 --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---

 +++ killed by SIGSEGV (core dumped) +++

 Speicherzugriffsfehler (Speicherabzug geschrieben)


Speicherzugriffsfehler = Segmentation fault

The problem is that vidcutter (or any dependency) try to dlopen the unversioned libGL.so whereas it should use libGL.so.1.

**Comment by martinkg** [comment]
i have built a new rpm Package [1] for Fedora with this patch [2]

[1] https://martinkg.fedorapeople.org/Packages/vidcutter/
[2] https://github.com/UnitedRPMs/vidcutter/blob/master/OpenGL_fix.patch

i will give a feedback if enduser had tested.

**Comment by martinkg** [comment]
this is the feedback from the enduser:

> Thanks a lot for the new vidcutter-package! Your efforts are highly appreciated!
> 
> Yes, I can fully confirm that hardware-acceleration + decoding works fine on my
> system. I'm using mpv with hwdec=vdpau and meanwhile even VLC set to
> vdpau-output works perfectly. Avidemux manages hardware-decoding with vdpau
> enabled also very well. Luckily no issues at all here! The open source drivers
> for the old entry level R5 230 are excellent and improve the performance in
> combination with the mesa-vdpau-drivers greatly.
> 
> Furthermore I'm very pleased I can also confirm that the vidcutter-rpm from
> 31.01.2018 works flawlessly for me now. Vidcutter doesn't crash anymore when
> I'm opening videofiles. I've done some testing with a couple of TV-recordings
> now and I have to say I'm quite impressed. Unfortunately Vidcutter seems a bit
> picky when it comes to the source-material, but that is another matter. The
> results with the Smart-Cut-feature (frame accurate cutting) were much, much
> better than I expected. Quite slow compared to Avidemux, but the cuts are
> absolutely clean, precise, with no pixelation or artifacts around the
> cutpoints. Practically invisible - I like that! ;-)  
> 
> A very fine piece of software and big, big thank you for adding it to rpmfusion
> and for all your help solving this issue so quickly.

**Comment by martinkg** [comment]
issue fixed with this [1] patch.
[1] https://github.com/UnitedRPMs/vidcutter/blob/master/OpenGL_fix.patch

**Comment by pmhahn** [comment]
'debian' is missing, too!
