### ISSUE TITLE
Vidcutter on 14.04 (Mint Kde 17.3) stop working recently

### ISSUE THREAD

**Issue by armageddon51** [ozmartian/vidcutter#15]
I use it a while ago but when I saw the new release 3, I relaunch it and it does not start anymore. I tried to re-install it but same thing. Tx

Error ;
maurice@KDE4-MINT:~ > vidcutter
Traceback (most recent call last):
  File "/usr/bin/vidcutter", line 9, in <module>
    load_entry_point('vidcutter==2.6.5', 'gui_scripts', 'vidcutter')()
  File "/usr/lib/python3/dist-packages/vidcutter/__main__.py", line 144, in main
    win = MainWindow()
  File "/usr/lib/python3/dist-packages/vidcutter/__main__.py", line 23, in __init__
    self.init_logging()
  File "/usr/lib/python3/dist-packages/vidcutter/__main__.py", line 49, in init_logging
    log_path = QStandardPaths.writableLocation(QStandardPaths.AppConfigLocation).lower()
AttributeError: type object 'QStandardPaths' has no attribute 'AppConfigLocation'

**Comment by ozmartian** [comment]
hi there @armageddon51 

please try updating once again to the latest version available in the PPA. v3 was only released for 14.04 ditros today as it required some heavy work to get all required dependencies into the PPA because they're not available in Ubuntu 14.04 standard packages (but they are as of 14.10 and above).

updating should now install latest VidCutter build along with a bunch of libmpv related packages. i've tested using a 14.04 liveCD myself but please confirm that it is now working if you dont mind so I can tick 14.04 related issues off my list :-)

many thanks!

**Comment by ChrisMayfield** [comment]
I had the same output on issue #9, and the update to version 3 fixed it. Thanks @ozmartian.

**Comment by armageddon51** [comment]
Hello my friend, hum sadly it is a no go with the new version 3. Please 
keep at it.

Thank you very much.

> maurice@KDE4-MINT:~ > vidcutter
> Traceback (most recent call last):
>   File "/usr/bin/vidcutter", line 9, in <module>
>     load_entry_point('vidcutter==3.0.0', 'gui_scripts', 'vidcutter')()
>   File "/usr/lib/python3/dist-packages/pkg_resources.py", line 351, in 
> load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2363, 
> in load_entry_point
>     return ep.load()
>   File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2088, 
> in load
>     entry = __import__(self.module_name, globals(),globals(), 
> ['__name__'])
>   File "/usr/lib/python3/dist-packages/vidcutter/__main__.py", line 
> 38, in <module>
>     from vidcutter.videocutter import VideoCutter
>   File "/usr/lib/python3/dist-packages/vidcutter/videocutter.py", line 
> 40, in <module>
>     import vidcutter.mpv as mpv
>   File "/usr/lib/python3/dist-packages/vidcutter/mpv.py", line 30, in 
> <module>
>     backend = CDLL(sofile)
>   File "/usr/lib/python3.4/ctypes/__init__.py", line 351, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: libass.so.5: cannot open shared object file: No such file or 
> directory

**Comment by mc4man** [comment]
Hmm, I think this was not the way to go about providing libmpv in 14.04. Copying out some packages from my ppa could produce unexpected results & put users in an awkward position. 
(- I did try your app in 14.04, it works fine but I use that ppa & some others in their entirety. Didn't try your ppa by itself as I'd need a fresh install..
By & large it's also overkill as libmpv is really just for decoding...

 I wish you'd asked me, maybe could of come up with a simpler solution.. For the moment I'd strongly suggest  you'd consider removing all 14.04 packages before it's too widespread, would help anyone that needs some  if ppa-purge can't make straight. 

Am currently seeing if libmpv will build against just default 14.04 libs., if so will provide link to test. 
Otherwise to use these libs you copied it would be far better to point to the jl2 ppa page & have users decide whether to use & use following instructions there...

**Comment by mc4man** [comment]
To note : not possible to do in 14.04 unless using much earlier mpv source or newer libav or ffmpeg then available in 14.04.

**Comment by ozmartian** [comment]
hi there...

i tested using a Trusty LiveCD so it was barebones and installating from PPA, after copying your packages, worked fine. Testing a few diferent video formats too... but you know best re all this, will wait for your response and then, failing that, probably just warn users, only Trusty is the problem and the portable bundled AppImage works perfectly on Trusty... am thinking thats an easier and safest option..

heeding your advice and cleaning trusty off the PPA now until further notice....

thanks for the alerting me to all this... would have contacted you if i had even the slightest inkling of the potential to cause damage i would have :-) thanks again, off to launchpad i go

**Comment by armageddon51** [comment]
Confirmed, the appimage works perfectly here. Mint Kde 17.3 (14.04)

Thanks !

**Comment by ozmartian** [comment]
gracias!
