### ISSUE TITLE
not able to install in Ubuntu 16.1

### ISSUE THREAD

**Issue by jsroyal** [ozmartian/vidcutter#17]
CLI:  LOG

jsroyal@Hp:~$ sudo add-apt-repository ppa:ozmartian/apps
 Various apps for public distribution
 More info: https://launchpad.net/~ozmartian/+archive/ubuntu/apps
Press [ENTER] to continue or ctrl-c to cancel adding it

gpg: keybox '/tmp/tmpymfcubdd/pubring.gpg' created
^[[Agpg: /tmp/tmpymfcubdd/trustdb.gpg: trustdb created
gpg: key 9BCA8B4F51A082C4: public key "Launchpad PPA for ozmartian" imported
^[[Agpg: Total number processed: 1
gpg:               imported: 1
N: Ignoring file '20auto-upgrades.ucf-dist' in directory '/etc/apt/apt.conf.d/' as it has an invalid filename extension
N: Ignoring file '20auto-upgrades.ucf-dist' in directory '/etc/apt/apt.conf.d/' as it has an invalid filename extension
N: Ignoring file '20auto-upgrades.ucf-dist' in directory '/etc/apt/apt.conf.d/' as it has an invalid filename extension
N: Ignoring file '20auto-upgrades.ucf-dist' in directory '/etc/apt/apt.conf.d/' as it has an invalid filename extension
N: Ignoring file '20auto-upgrades.ucf-dist' in directory '/etc/apt/apt.conf.d/' as it has an invalid filename extension
OK
jsroyal@Hp:~$ sudo apt-get update
N: Ignoring file '20auto-upgrades.ucf-dist' in directory '/etc/apt/apt.conf.d/' as it has an invalid filename extension
E: Could not get lock /var/lib/apt/lists/lock - open (11: Resource temporarily unavailable)
E: Unable to lock directory /var/lib/apt/lists/
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
jsroyal@Hp:~$ sudo apt-get install vidcutter
N: Ignoring file '20auto-upgrades.ucf-dist' in directory '/etc/apt/apt.conf.d/' as it has an invalid filename extension
E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
jsroyal@Hp:~$ 

Help me to install :)

**Comment by cas--** [comment]
Definitely not a vidcutter issue... See [AskUbunutu](http://askubuntu.com/q/15433/8570)

**Comment by jsroyal** [comment]
@cas-- thank for giving a link but I did not get anything from it.So what is the problem here can help figure it out.
So how can install this application?

**Comment by cas--** [comment]
Did you try running update again? You will only be able to install once you fix that `apt/dpkg` error that is preventing the update and install. As I said it has nothing to do with vidcutter and afraid I cannot offer any more help but you can search and ask on Ubuntu forums etc...

**Comment by ozmartian** [comment]
@jsroyal 

it looks to me like you have some older package(s) that did not install, with broken dependencies which will continue everytime you use the apt tools until resolved... nothing to do with VidCutter...

e.g. '20auto-upgrades.ucf-dist'   <--- there is no file with this name in the entire VidCutter repository/codebase.. 

the first thing i would do if i were you is move that file out of the apt configuration folders so that it stops these errors from occurring... don't delete the file but instead:

  $ sudo mv /etc/apt/apt.conf.d/20auto-upgrades.ucf-dist ~/ 

which moves it into our home directory folder... then you can have a look inside to determine what it is, where it came from etc.. priority is to get your apt framework working properly.. you should then be able to install VidCutter without fail..

also, you may need to manually delete the apt lock files if it crashed midway through a package installation, throwing an error as if you have an install process already running in another window.. if it complains about apt already running, which it isn't, clear lock files with:

 $ sudo rm /var/cache/apt/archives/lock /var/lib/dpkg/lock

good luck :-)

**Comment by jsroyal** [comment]
@ozmartain thank you for help. I will try and come back.
