### ISSUE TITLE
Minimum application size for low resolution screens

### ISSUE THREAD

**Issue by cas--** [ozmartian/vidcutter#21]
Opening vidcutter on my eeepc I found that the application minimum size is just too big for my screen (1024x600) and it cannot be resized smaller:

![vidcut_offscreen](https://cloud.githubusercontent.com/assets/606038/23806818/1c06fc50-05bb-11e7-9580-b7a601276a6b.png)

A smaller minimum size setting would be much appreciated, thanks :)

**Comment by ozmartian** [comment]
@cas-- 
leave this with me.... i can put in some code code to check the viewport size on app launch, if its a small screen then it can readjust itself to a smaller size ratio as well as shrinking imagery so that it looks correct...

should have the done within a day or so and can make a beta package available for you to test... what is that device you're running on out of curiosity? something like an eeePC?

**Comment by cas--** [comment]
That would be fine too, I think it still needs a minimum size to allow the user to resize it down but set the initial size larger. 

Yes it is an eeepc :)

**Comment by ozmartian** [comment]
closing this as it was done since last version or two... please reopen or file new issue if still not working for you

**Comment by zx6802** [comment]
![vidcutter-window-size-on-hp-mini-5101](https://user-images.githubusercontent.com/28398691/27442906-da830b4e-5771-11e7-8d53-6664ec3d1537.png)
I'm trying to use VidCutter 3.5.0 on a HP Mini 5101 which has a 1366x768 resolution under Lubuntu 16.10 and here the problem seems to persist.
