### ISSUE TITLE
Add ability to force stream-copy

### ISSUE THREAD

**Issue by lsde** [ozmartian/vidcutter#249]
Hi,
sometimes (like in audiovisual archiving institution), one needs a really lossless cut (not reencode), so there should be an option (a button like SmartCut perhaps?) to force stream-copy.

The cutting logic it's trivial (just add condition here):
https://github.com/ozmartian/vidcutter/blob/793127c521b18f0bab19b67bc42e8da16a667afd/vidcutter/libs/videoservice.py#L297

GUI is a different question (as I'm not a QT developer, otherwise I'd submit a pull-request right-away).

btw, do you know of [LosslessCut](https://github.com/mifi/lossless-cut) ?
It has a simillar goal (it's doing really lossless cuts), but it's written in Electron which sucks :(

Keep up the good work!

PS: or what about just dropping the reencode and doing -c copy by default? :)

**Comment by ozmartian** [comment]
With smart cut disabled there is NO re-encoding. Its lossless but less frame accurate. have you actually used the application?!


---- On Wed, 25 Sep 2019 19:17:52 +1000 lsde <notifications@github.com> wrote ----


Hi,
 sometimes (like in audiovisual archiving institution), one needs a really lossless cut (not reencode), so there should be an option (a button like SmartCut perhaps?) to force stream-copy.
The cutting logic it's trivial (just add anothe condition here):
 https://github.com/ozmartian/vidcutter/blob/793127c521b18f0bab19b67bc42e8da16a667afd/vidcutter/libs/videoservice.py#L297
GUI is a different question (as I'm not a QT developer, otherwise I'd submit a pull-request right-away).

btw, do you know of https://github.com/mifi/lossless-cut ? It has a simillar goal (it's doing really lossless cuts), but it's written in Electron which sucks :(

Keep up the good work!

PS: or what about just dropping the reencode and doing -c copy by default? :)

**Comment by lsde** [comment]
oh sorry!
I've enabled SmartCut right-away and had an impression it doesn't affect the processing, as there's no information in the settings.
