### ISSUE TITLE
Native file chooser dialog on Ubuntu

### ISSUE THREAD

**Issue by cas--** [ozmartian/vidcutter#27]
I think there is a Qt5 issue showing native dialogs on Ubuntu 16.04 as you can see here the Nautilus and File Chooser dialog don't match and it's hard to navigate to mounts:

![selection_049](https://cloud.githubusercontent.com/assets/606038/23827850/ba84e41e-06b5-11e7-9176-baf2511df3cc.png)

Possibly similar to this: https://github.com/evpo/EncryptPad/issues/46

**Comment by ozmartian** [comment]
Hi @cas-- 

The latest version 3.2.0 features a "Use native dialogs" option in the settings menu. This should help with what you report. Can I confirm that if you're installing via PPA or using the AppImage because I think I have seen that before with AppImage and will need to seek a solution as its a minor bug unless I am doing something wrong when creating the AppImages themselves.

Let us know, thanks!

**Comment by cas--** [comment]
This is with the PPA actually and changing that option seems to make no difference. However I just checked the version of Qt and it's quite old compared to 5.8 mentioned in that other ticket:

```
libmpv: 0.14.0     FFmpeg: 2.8.10 
Python: 3.5.2     PyQt5: 5.5.1     SIP: 4.17 
```

Unable to test appimage as I'm getting an import error with `six`...

**Comment by ozmartian** [comment]
@cas-- 

5.5.1 is still not that bad... I did some testing and i think what is actually the problem is Ubuntu's Qt5 library for that earlier version. From your screenshots I can see that you are in fact getting the native dialog because the Ubuntu theme colours and folder icons are there so there is nothign actually wrong from the app's end. I see the same dialog when testing under Ubuntu Trusty or even Willy from memory. Its obviously some Qt only file dialog because other GTK based apps dont seem that way. You should still be seeing a difference using the native dialogs with colours and icons I think but its the non-native Qt custom dialog is about the same as what you are seeing re the left side pane only having Computer and home.

The app starts from your home folder by default so you should see your standard folders right away. I think you can set bookmarks on what you have though so wouldn't be a big effort to make it a bit more usuable. If you have any other Qt-based apps they should be behaving the same.

As always, do let me know if all I have said is a steaming pile of **** and I need to keep investigating :-)
