### ISSUE TITLE
Project file broken

### ISSUE THREAD

**Issue by michael-heerdegen** [ozmartian/vidcutter#272]
Hi,

I'm using v6.0.0-flatpak on Debian.  Thanks for writing this tool.  I checked that this is not a duplicate:

Several times I loaded different media files, selected two clips, and saved the project file.  I get a file like this:

```
595.094000	842.675000	0
1205.579000	1373.205000	0
```
Isn't there a reference to the media file missing?  Anyway, in whichever way I try to load this .vcp from Vidclipper, I get the error message:

Invalid entry at line 2:

1205.579000	1373.205000	0

even when I load the respective media file before.

TIA,

Michael.

**Comment by tontof** [comment]
Same problem.
You can fix the file project adding absolute file on first line and chapter title separate by tab at end of each line.
For example
```
/path/to/your/file.mp4
595.094000	842.675000	0	""
1205.579000	1373.205000	0	""
```

**Comment by Perkolator** [comment]
Why was this closed? Every project file created by the latest version (6.0.5.1) can not be opened, always "Invalid entry at line 2" error. I even tried @tontof suggestion but that didn't work for me.

**Comment by n-st** [comment]
I've had a look at why this is happening. This problem has a few layers:

### Background:
VidCutter supports two project file formats: EDL and (since v3.2.0) VCP.
The format you're currently seeing in saved project files is EDL (no filename, no `""` chapter name at the end of each line).

Upon loading, VidCutter checks the file's extension, sees ".vcp" and tries to parse the (EDL-formatted) file as a VCP file — which fails because the syntax doesn't match.
cf. [syntax definition](https://github.com/ozmartian/vidcutter/blob/7ddda2c5168a4a03c40f979939e87efd0f8898ae/vidcutter/videocutter.py#L127-L130), [project file reader](https://github.com/ozmartian/vidcutter/blob/7ddda2c5168a4a03c40f979939e87efd0f8898ae/vidcutter/videocutter.py#L833-L879)

But why does it write an EDL file when you have selected VCP in the save dialog?
[`saveProject(…)`](https://github.com/ozmartian/vidcutter/blob/7ddda2c5168a4a03c40f979939e87efd0f8898ae/vidcutter/videocutter.py#L930-L963) uses a different method to determine file types: Instead of the file extension, it checks which filter was selected in the save dialog's filetype dropdown.
Specifically, it checks if the filter name is "VidCutter Project (*.vcp)".
However, the save dialog (and open dialog, for that matter) [is configured to hide the "filter details"](https://github.com/ozmartian/vidcutter/blob/7ddda2c5168a4a03c40f979939e87efd0f8898ae/vidcutter/videocutter.py#L688), i.e. the "(*.vcp)" part of the filter name.
Thus the filter name can *never* match "VidCutter Project (*.vcp)", and the project is always saved in the EDL format.

### Workaround?
So what if we just rename the project file to something.edl and load that?
You'll see "project loaded" on the OSD, but the clip list will remain empty…
… until you create another clip, that is.

VidCutter does load the project file correctly; it just doesn't refresh the clip list afterwards.
Adding `self.renderClipIndex()` after [this line](https://github.com/ozmartian/vidcutter/blob/7ddda2c5168a4a03c40f979939e87efd0f8898ae/vidcutter/videocutter.py#L885) should fix that.

### Suggested fix:
Determine the save file format based on the file extension, since that approach is already used when loading a file.
Not very "Unix-y" and not robust against old project files that were created with a VCP extension but EDL content, but it's the simplest step forward for now. At a later point, the loading process could be improved to deal with both supported formats gracefully, regardless of the file extension (we're already throwing regexes at the file, so it's not a huge issue to try multiple ones, or modify them to match both file formats).

**Comment by JohnDoe-JohnDoe** [comment]
I have freshly installed v6.0.5.1 on two laptops, both Win10 64bit. When I save the project, one creates a file in this format:
C:/path/to/your/file.mp4
595.094000	842.675000	0	
1205.579000	1373.205000	0	
Which cannot be loaded (without editing as said by tontof)
The other creates a file:
C:/path/to/your/file.mp4
595.094000	842.675000	0	""
1205.579000	1373.205000	0	""
Which works fine.
