### ISSUE TITLE
Error during save media with accurate frame cutting enabled

### ISSUE THREAD

**Issue by jozseflehocz** [ozmartian/vidcutter#290]
Hello,
If accurate frame cutting is enabled, then media could not be saved:
`/usr/bin/ffprobe -hide banner - error show packetS -select streams v -show entries packet=pts time, flags of csv Vhome/local/AD/ lehocz.jozsef/Videos/obs/2020-09-21 10-19-31.mkv" File "/usr/lib/python3/dist-packages/vidcutter/

videocutter.py", line 1363, in saveMedia

self. smartcutter(file, source file, source ext)

File "/usr/lib/python3/dist-packages/vidcutter/

video cutter-py", line 1413, in smartcutter allstreams-True) File "/usr/lib/python3/dist-packages/vidcutter/ tibs/videoservice.py". Line 331, in smartcut bisections = self.getGO bisectors(source,

start, end)

File "/usr/lib/python3/dist-packages/vidcutter/ libs/videoservice.py". line 590, in getGO bisections end_pos = bisect_left(keyframes, end)

<class TypeError'>: < not supported between

instances of 'str and 'float`
Op system:  Pop OS! (Ubuntu) 19.04
Vidcutter version 6.0.0

**Comment by funkypitt** [comment]
I have the same issue.

**Comment by ozmartian** [comment]
Please retry w/ v6.0.5.1 and re-open/comment if the same still occurs.

Thx!

**Comment by zykure** [comment]
I had the same issue today with recent version 6.0.5.1 installed on Manjaro Linux (Python 3.10.4, libmpv 109.1). The error is reproducible when I open the same project file again, as long as SmartCut mode is enabled. Luckily this is fixable with a few code edits.

Log output:
```
2022-06-08 12:14 - root - CRITICAL -   File "/usr/lib/python3.10/site-packages/vidcutter/videocutter.py", line 1361, in saveMedia
    self.smartcutter(file, source_file, source_ext)
  File "/usr/lib/python3.10/site-packages/vidcutter/videocutter.py", line 1406, in smartcutter
    self.videoService.smartcut(index=index,
  File "/usr/lib/python3.10/site-packages/vidcutter/libs/videoservice.py", line 331, in smartcut
    bisections = self.getGOPbisections(source, start, end)
  File "/usr/lib/python3.10/site-packages/vidcutter/libs/videoservice.py", line 590, in getGOPbisections
    end_pos = bisect_left(keyframes, end)

2022-06-08 12:14 - root - CRITICAL - <class 'TypeError'>: '<' not supported between instances of 'str' and 'float'
```

I did some debugging and traced the issue down to a wrongly formatted keyframe timestamp. All keyframes are given as float values, except the last one which is a string in `H:MM:SS.nnn` format. Hence, the comparison operator fails as indicated in the error message. In my case, the `keyframes` object in the `getGOPbisections()` method contains:
```
[0.0, 12.5, 20.6 ... 5575.35, 5587.85, 5600.35, 5612.85, '1:33:36.300']
```

I was able to add a workaround that simply converts all timestamps to floats, but the actual issue is probably somewhere in the `getKeyframes()` method which produces the non-float value. Updated code in `videocutter.py`:
```
    def getGOPbisections(self, source: str, start: float, end: float) -> dict:
        keyframes = self.getKeyframes(source)
        keyframes = [ (sum([ float(v)*60**i for i,v in enumerate(reversed(f.split(':'))) ]) if type(f) == str else f) for f in keyframes ]  # hacky solution
        #print(start, end, keyframes)
```

**Comment by KLudwig-V** [comment]
Still the same problem in September 2022...
