### ISSUE TITLE
vidcutter : lossless without re-encode?

### ISSUE THREAD

**Issue by Clemens-Ratte-Polle** [ozmartian/vidcutter#306]
hi
does it save cut videos without reencode?
thx

**Comment by ozmartian** [comment]
Yes, that is the point of the application. But, you will have issues regarding cut accuracy depending on the amount of keyframes in the original (source) video. You can only cut at keyframes without reencoding video. A SmartCut option exists which takes longer because it reencodes only a small portion at the start and end of the video cut, inserts a large middle segment as is to produce a more accurate cut at the exact point you want, but that again sometimes does not work depending on the original video and how it is put together.





---- On Thu, 15 Apr 2021 00:31:32 +1000 Clemens Ratte-Polle ***@***.***> wrote ----




hi
 does it save cut videos without reencode?
 thx
