### ISSUE TITLE
Snap 6.0.5 version on Unbuntu 3.0.5 Save Freeze / Cannot read project file

### ISSUE THREAD

**Issue by betrixed** [ozmartian/vidcutter#312]
Has a PyQt interface.
Installed through a snap package.
Pity about 1) Cannot read its own simple text project file.
The file only had 3 lines with 3 time stamp ranges, for 3 snippets.
I was surprised to not see the file name of the file being edited was not in the project file.
2) Saving Media halts at 66%, ie only one works for one clip, although can select multiple.
This utility has nice selection and play features, but this is not good enough for a simple of saving, executing and reading the project file. This was regardless of "smart cut" setting.
If it is going to fail, it should fail straight away, not after wasting my time.

**Comment by ozmartian** [comment]
Please try again with latest 6.0.5.1 Snap release. That should fix the 2nd issue. I'll have to test the project file issue, must be a Snap sandboxing issue, should be easy to resolve.

If you're on Ubuntu 20+ I'd recommend using the launchpad PPA native installation to avoid issues due to Snap restrictions while I get them ironed out.

**Comment by ozmartian** [comment]
The latest Snap 6.0.5.1 has been tested and reported to be working fine by others so awaiting your feedback before closing this issue off. Thx

**Comment by muzena** [comment]
@ozmartian 
1) Cannot read its own simple text project file.
I have this problem, on Vidcutter 6.0.5.1 version installed from PPA on Linux Mint 20.3.
