### ISSUE TITLE
Output file successfully 'ready', but 0 bytes.

### ISSUE THREAD

**Issue by albaphysic** [ozmartian/vidcutter#32]
Ubuntu 16.10
VidCutter 3.0.1

Vidcutter runs `/usr/bin/ffmpeg -i "file.mp4" -ss 00:00:00.000 -t 02:04:29.995 -vcodec copy -acodec copy -map 0 -y "file_EDIT.mp4"`

Which in Vidcutter shows as successfully clipped, though the saved output file is empty.

If I run that command manually, ffmpeg returns the following error:

`Stream mapping:`
`  Stream #0:0 -> #0:0 (copy)`
`  Stream #0:1 -> #0:1 (copy)`
` Stream #0:2 -> #0:2 (mov_text (native) -> ? (?))`
`Encoder (codec none) not found for output stream #0:2`

Workaround: I changed the map flag to only process the first two streams `-map 0:0 -map 0:1`

**Comment by cas--** [comment]
See #26 and #23

**Comment by ozmartian** [comment]
@albaphysic 

The next version will include options for selecting which streams you included. Basically surfacing the ffmpeg map arguments to the GUI in an advanced settings dialog which will address this issue which is really due to source media not being properly indexed.

Subtitle streams like the one you mention here has been dealt with already thought. Version 3.2.0 will most likely work for you "out of the box"...
