### ISSUE TITLE
Is there no portable package for Windows?

### ISSUE THREAD

**Issue by pstein** [ozmartian/vidcutter#350]
I prefer to use a portable installation.

As far as I remember there was a *.zip package available for download in the past.

Where is it?

**Comment by ozmartian** [comment]
Latest Windows installer is always available at https://github.com/ozmartian/vidcutter/releases

**Comment by pstein** [comment]
Yes, I know.

But I am searching for a PORTABLE package which need to be extracted only.

**Comment by ruboard** [comment]
> Latest Windows installer is always available at https://github.com/ozmartian/vidcutter/releases


There is a strange response: the program has an option to select a folder with ffmpeg, however, when launching, the program unpacks itself into temp along with its built-in ffmpeg. It's completely unclear why you don't create a portable version in this case. It would be much more convenient for many users to specify their own path, while also having a smaller program size. Not to mention that ffmpeg is often already installed in the system. So, the presence of this option seems at least illogical!

**Comment by ruboard** [comment]
> You can specify your own path to the tools used in Settings -> Tools

I specifically wrote about this, meaning that the built-in and far from fresh FFmpeg libraries inside your wonderful program are completely unnecessary, since a huge number of users would prefer to use this option and specify their own, or will want to automatically use the ones set in the Windows environment variables.
