### ISSUE TITLE
ImportError: libmpv version is incorrect. Required 1.109 got 1.107.

### ISSUE THREAD

**Issue by slamer59** [ozmartian/vidcutter#356]
Hello, I just install it from snap

**Comment by ozmartian** [comment]
This is due to snap's still using old libraries in their core. I'll have to set some time aside to get this working again.



In the meantime, I have update the PPA for latest Ubuntu releases so you could install from there, its much better anyways.



$ sudo add-apt-repository ppa:ozmartian/apps
$ sudo apt update
$ sudo apt install vidcutter

Cheers









---- On Sun, 08 May 2022 21:41:28 +1000 Thomas PEDOT ***@***.***> wrote ----





Hello, I just install it from snap

**Comment by ozmartian** [comment]
Hi again,

I've just released a new build to the Snap store which should fix this issue once and for all. It takes a few hours for them to be published so please update the snap when prompted or try a manual snap update in a few hours. Let me know how you go.

Thx!

**Comment by ozmartian** [comment]
Latest snap fixed and verified to work. I still recommend using it via the PPA though.

**Comment by slamer59** [comment]
Sorry for the delay ! Yes it works :) Thanks !
