### ISSUE TITLE
Make vidcutter to not extract ffmpeg and other libs on every boot

### ISSUE THREAD

**Issue by Andryshik345** [ozmartian/vidcutter#372]
Since i have them installed on my system already, there's no need to extract them every time to temporary folder, it is just a waste of my SSD resources. Forcing custom paths in settings didn't help, so is there any way to make it use my binaries? And i think it also would make it launch faster.

**Comment by ozmartian** [comment]
Thats how Windows works. All applications use their own version of libs. You can however set the path to your own binaries of the libs in the Settings menu.






---- On Thu, 09 Feb 2023 01:35:51 +1100 GooseWing ***@***.***> wrote ---





Since i have them installed on my system already, there's no need to extract them every time to temporary folder, it just waste of my SSD. Forcing custom paths in settings didn't help, so is there any way to make it use my binaries? And i think it also would make it launch faster.

**Comment by Andryshik345** [comment]
> Thats how Windows works. All applications use their own version of libs. You can however set the path to your own binaries of the libs in the Settings menu.

So if I can set the path to my own libraries, why not stop unpack the built-in ones and use my own instead?

**Comment by ozmartian** [comment]
That is not how Windows application packaging works. Its does for Linux but Windows doesn't work that way. Every application you install comes with its own dependencies prepackaged. Its a nightmare to do it the way you suggest due to everyone's setup being so different and not standardized. VidCutter lets you set paths to your own incase you want to use a newer version of the dependencies. We are talking about an extra 50-60Mb of files, hardly something to worry about in 2023. All video editing apps on Windows works this way.







---- On Thu, 09 Feb 2023 14:09:00 +1100 GooseWing ***@***.***> wrote ---





Thats how Windows works. All applications use their own version of libs. You can however set the path to your own binaries of the libs in the Settings menu.


So if I can set the path to my own libraries, why not stop unpack the built-in ones and use my own instead?

**Comment by Andryshik345** [comment]
Well, ok then, now I understand. Thanks for the explanation.
