### ISSUE TITLE
Add a short description fo the software on top of the README page

### ISSUE THREAD

**Issue by unfa** [ozmartian/vidcutter#388]
Hi!

I just found this project and I'm trying to learn what it is, what it can do and if it'll suit my needs.

However I see no information about this anywhere in the README. I think that makes potential new users just pass by, because they don't get to know what they'd be getting themselves into if they spend their time learning the program.

The README seems to only cover how to get the software running, saying nothing about what the software is. Not even a sentence!

**Comment by ozmartian** [comment]
Its a video cutter & joiner using FFMpeg as it's backed and Qt for the frontend. Not sure what more you expect? In the 6 years since launch no one has expresses your concerns so find it confusing.






---- On Mon, 31 Jul 2023 19:29:43 +1000 unfa ***@***.***> wrote ---





Hi!

I just found this project and I'm trying to learn what it is, what it can do and if it'll suit my needs.

However I see no information about this anywhere in the README. I think that makes potential new users just pass by, because they don't get to know what they'd be getting themselves into if they spend their time learning the program.

The README seems to only cover how to get the software running, saying nothing about what the software is. Not even a sentence!

**Comment by unfa** [comment]
Ah! That says a lot!
Is it strictly linear or can you for example merge a video with an audio track and truncate/offset them separately?

This information on the front page would have already made me more interested :)

**Comment by ozmartian** [comment]
Hi again,



I'd recommend you use a video editor rather than VidCutter for your needs. VidCutter allows you to disable audio and subtitle tracks but full editing liking adding tracks and offsetting. As per screenshot example here:



***@***.***/images/vidcutter-03.png



Cheers.






---- On Tue, 01 Aug 2023 00:34:07 +1000 unfa ***@***.***> wrote ---





Ah! That says a lot!
 Is it strictly linear or can you for example merge a video with an audio track and truncate/offset them separately?
This information on the front page would have already made me more interested :)

**Comment by unfa** [comment]
Thanks. I've used many different libre NLEs for years (Blender, Kdenlive, Olive...) and I need something simpler that won't be so crashy :D I'm checking out Avidemux, but will also try out VidCutter and see how I can use it.
