### ISSUE TITLE
Github release version isn't uniform with CHANGELOG

### ISSUE THREAD

**Issue by luzpaz** [ozmartian/vidcutter#405]
Current release is 6.0.5.1 (https://github.com/ozmartian/vidcutter/releases/tag/6.0.5.1)
https://github.com/ozmartian/vidcutter/blob/f6bc214f6efe1219e84974ef21ffd3f8781dd9c5/CHANGELOG#L1

**Comment by ozmartian** [comment]
CHANGELOG is still valid. All changes since have been specific to Arch Linux packaging fixes etc. The next release of VidCutter, which will switch to Qt6, will have an updated CHANGELOG reflecting all changes and fixes.

**Comment by luzpaz** [comment]
That's great news! Thank you for the reply

**Comment by a17r** [comment]
> The next release of VidCutter, which will switch to Qt6

### Qt5 is now declared deprecated in Gentoo

At this point in time, Linux distributions are starting to track which packages are blocking a future Qt5 cleanup. Real Qt Company OSS support stopped back in 2020, when public availability of LTS releases started to be delayed for 1 year, stable branch repository access got closed down (with 5.15 branch repository receiving any new LTS tag one year after commercial release) and only Qt6-relevant bugs are being fixed (then backported) since then. The final release happened on 2025-05-19, which means a) we will not get it until 2026-06-19, b) any bugs discovered since last May will not be fixed and c) no bugs since 2020-12-08 that haven't also been affecting Qt6 were fixed at all.

*At least* Gentoo, Alpine and Ubuntu are entertaining Qt5 porting trackers by now, for Gentoo, Qt5 revdep cleanups are in full swing already.
https://bugs.gentoo.org/show_bug.cgi?id=qt5-removal
https://gitlab.alpinelinux.org/alpine/aports/-/issues/17114
https://ubuntu-archive-team.ubuntu.com/transitions/html/qt5-removal.html
