### ISSUE TITLE
Vidcutter does not start if username contain a capital letter.

### ISSUE THREAD

**Issue by Abhinav1217** [ozmartian/vidcutter#64]
I installed vidcutter using the copr mentioned in readme. When running it, It gives following error.

```
[Abhinav@fedora-25 ~] $ vidcutter 
Traceback (most recent call last):
  File "/usr/bin/vidcutter", line 9, in <module>
    load_entry_point('vidcutter==3.5.0', 'gui_scripts', 'vidcutter')()
  File "/usr/lib/python3.5/site-packages/vidcutter/__main__.py", line 301, in main
    win = MainWindow()
  File "/usr/lib/python3.5/site-packages/vidcutter/__main__.py", line 51, in __init__
    self.init_logger()
  File "/usr/lib/python3.5/site-packages/vidcutter/__main__.py", line 102, in init_logger
    os.makedirs(log_path, exist_ok=True)
  File "/usr/lib64/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib64/python3.5/os.py", line 231, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib64/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/abhinav'
Segmentation fault (core dumped)
```

Before this I tried using AppImage. But it was giving Python QT error.

**Comment by Abhinav1217** [comment]
Still getting same permission error when using copr. Using latest 5.0.0,   Maybe it has something to do with Wayland. 
```
[Abhinav@fedora-26 ~] $ vidcutter --debug

Traceback (most recent call last):
  File "/usr/bin/vidcutter", line 11, in <module>
    load_entry_point('vidcutter==5.0.0', 'gui_scripts', 'vidcutter')()
  File "/usr/lib64/python3.6/site-packages/vidcutter/__main__.py", line 379, in main
    win = MainWindow()
  File "/usr/lib64/python3.6/site-packages/vidcutter/__main__.py", line 58, in __init__
    self.init_settings()
  File "/usr/lib64/python3.6/site-packages/vidcutter/__main__.py", line 145, in init_settings
    os.makedirs(settings_path, exist_ok=True)
  File "/usr/lib64/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib64/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/usr/lib64/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/abhinav'
[Abhinav@fedora-26 ~] $ 
```

**Comment by ferdnyc** [comment]
vidcutter is trying to create the directory `/home/abhinav/.config/vidcutter` to store its settings, but is unable to do so because of a permissions issue. Are you running the application as the correct user?

You can try running `mkdir -p /home/abhinav/.config/vidcutter` from a command shell, and you'll (most likely) get the same permissions error trying to create that directory. You need to fix the permissions on either `/home/abhinav` or `/home/abhinav/.config` to allow creation of the settings files.

**Comment by Abhinav1217** [comment]
Ok, I guess it has something to do with my username containing a capital letter. My home directory is `/home/Abhinav/` .   I did create a folder at ~/.config/vidcutter. But when It didn't solve, I posted error here.  I guess the program convert string to lowercase when searching for home directory. 

So I guess issue is not because of fedora but because of my username containing a Capital letter. I should check on my other distros if this is the cause.

**Comment by ferdnyc** [comment]
You are _quite_ correct! The code in `vidcutter/__main__.py` lines 106-116 reads:
```python
 def init_logger(self) -> None:
        try:
            log_path = QStandardPaths.writableLocation(QStandardPaths.AppConfigLocation).lower()
        except AttributeError:
            if sys.platform == 'win32':
                log_path = os.path.join(QDir.homePath(), 'AppData', 'Local', qApp.applicationName().lower())
            elif sys.platform == 'darwin':
                log_path = os.path.join(QDir.homePath(), 'Library', 'Preferences', qApp.applicationName()).lower()
            else:
                log_path = os.path.join(QDir.homePath(), '.config', qApp.applicationName()).lower()
        os.makedirs(log_path, exist_ok=True)
```

Note the ample use of `.lower()` to force path elements to lower-case. That's fine for the `qApp.applicationName()`, but **not** for the `QStandardPaths.writableLocation(QStandardPaths.AppConfigLocation)`, which should be rooted at the user's `$HOME` and absolutely _could_ contain uppercase characters which need to be preserved, at least on macOS and Linux where paths are case-sensitive.

This is a vidcutter bug. I would suggest changing the Issue title to something like, "vidcutter lowercases config path, breaks for usernames containing capital letters", as that's the real problem here.

**Comment by Abhinav1217** [comment]
Just changing the title to more appropriate.  I tested it in ubuntu too. While Ubuntu does not allow Capitalised username during installation, I could however create it using terminal once installed. 

Fully lower case is kind of an "unofficial" unix way to do things, but a lot of windows convert like me still has a habit of capitalised folders and file name, and username. 

*__Update__*
With a Lower case username home directory, It is working as expected. 
Also Appimage on Fedora is still giving Python Qt error.  It does run on Ubuntu.
